<a href="https://colab.research.google.com/github/dacq-trap/MachineLearningWorkshop/blob/main/%E7%AC%AC3%E5%9B%9E(%E3%83%81%E3%83%BC%E3%83%88%E3%82%B7%E3%83%BC%E3%83%88).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Pandas チートシート

## Numpy

参考資料 [16. NumPy (1): ベクトル — Python早見帳](https://chokkan.github.io/python/16numpy1.html)

ndarrayというものを扱ってベクトルとか行列を操作する

In [ ]:
import numpy as np

基本は`np.array`

In [ ]:
# ベクトル
a = np.array([1,2,3,4,5])
b = np.array([7,8,9,10,11])
a

array([1, 2, 3, 4, 5])

In [ ]:
# 行列
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,3,2], [4,3,1], [1,3,4]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# rangeからもできる
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### アクセスいろいろ

In [ ]:
a[0]

1

In [ ]:
# 0, 1, 2番目の要素にアクセス
a[[0,1,2]]

array([1, 2, 3])

In [ ]:
# 条件
a>1

array([False,  True,  True,  True,  True])

`&`(and) とか`|`(or)とか`~`(not)

In [ ]:
(a>1) & ~(a>3)

array([False,  True,  True, False, False])

条件で選択できる

In [ ]:
a[a>1]

array([2, 3, 4, 5])

In [ ]:
print('行0', A[0])
print('列0', A[:,0])
print('(0,0)の要素', A[0,0])

行0 [1 2 3]
列0 [1 4 7]
(0,0)の要素 1


なんかこういうのもできる

In [ ]:
A[:,[0,1,2]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

listへの変換

In [ ]:
a.tolist()

[1, 2, 3, 4, 5]

要素数は`shape`

In [ ]:
a.shape

(5,)

In [ ]:
A.shape

(3, 3)

四則演算

In [ ]:
a+b

array([ 8, 10, 12, 14, 16])

In [ ]:
A+B

array([[ 2,  5,  5],
       [ 8,  8,  7],
       [ 8, 11, 13]])

In [ ]:
b-a

array([6, 6, 6, 6, 6])

In [ ]:
B-A

array([[ 0,  1, -1],
       [ 0, -2, -5],
       [-6, -5, -5]])

In [ ]:
a*b

array([ 7, 16, 27, 40, 55])

In [ ]:
A*B

array([[ 1,  6,  6],
       [16, 15,  6],
       [ 7, 24, 36]])

`*`は各要素ごとの積になる

In [ ]:
a/b

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545])

In [ ]:
A/B

array([[1.        , 0.66666667, 1.5       ],
       [1.        , 1.66666667, 6.        ],
       [7.        , 2.66666667, 2.25      ]])

内積

In [ ]:
a.dot(b)

145

In [ ]:
a @ b

145

外積

In [ ]:
np.outer(a,b)

array([[ 7,  8,  9, 10, 11],
       [14, 16, 18, 20, 22],
       [21, 24, 27, 30, 33],
       [28, 32, 36, 40, 44],
       [35, 40, 45, 50, 55]])

行列積

In [ ]:
A.dot(B)

array([[12, 18, 16],
       [30, 45, 37],
       [48, 72, 58]])

In [ ]:
A@B

array([[12, 18, 16],
       [30, 45, 37],
       [48, 72, 58]])

転置

In [ ]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

ベクトルはそのまま転置できない

In [ ]:
a.T

array([1, 2, 3, 4, 5])

`np.newaxis`でベクトルから次元を増やすことができる

In [ ]:
a[np.newaxis,:]

array([[1, 2, 3, 4, 5]])

In [ ]:
a[:,np.newaxis]
# a[:,np.newaxis].shape -> (5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# こういう外積も可
a[:,np.newaxis].dot(b[np.newaxis,:])

array([[ 7,  8,  9, 10, 11],
       [14, 16, 18, 20, 22],
       [21, 24, 27, 30, 33],
       [28, 32, 36, 40, 44],
       [35, 40, 45, 50, 55]])

平均とか分散とか

In [ ]:
print('a', np.mean(a))
print('A', np.mean(A))
print('A', np.mean(A, axis=0))
print('A', np.mean(A, axis=1))

a 3.0
A 5.0
A [4. 5. 6.]
A [2. 5. 8.]


In [ ]:
# 分散，標準偏差
np.var(A), np.std(A)

(6.666666666666667, 2.581988897471611)

axisで方向を指定して平均したりする　超重要

行列のランク

固有値とか行列の数学っぽいことは`linalg`でやる　詳細はググって

In [ ]:
print('rank of A is ', np.linalg.matrix_rank(A))
print('rank of B is ', np.linalg.matrix_rank(B))

rank of A is  2
rank of B is  3


行列積

In [ ]:
np.linalg.det(A)

0.0

floatの関係で0にはならないけど実質0

逆行列

In [ ]:
B_ = np.linalg.inv(B)

In [ ]:
B @ B_

array([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
       [-2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
# pinv 擬似逆行列
A_ = np.linalg.pinv(A)

In [ ]:
A @ A_ @ A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

単位行列

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

すべての要素が1

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

その他

`np.random`で乱数関係色々使える

In [ ]:
print('多分一様乱数', np.random.randint(10))
print('ガウス分布に従う乱数', np.random.normal())
print('range(10)からランダムに選択とか…', np.random.choice(range(10), size=10))

多分一様乱数 8
ガウス分布に従う乱数 1.3834582253598415
range(10)からランダムに選択とか… [1 3 3 5 7 7 7 7 8 7]


sin,cosとか

In [ ]:
np.sin(np.pi/2)

1.0

In [ ]:
np.arccos(0)*2

3.141592653589793

## pandas

参考 https://utokyo-ipp.github.io/7/7-1.html

- エクセルとかcsvみたいなやつを扱う`pd.DataFrame`
- ベクトルみたいに一次元のときは`pd.Series`

In [ ]:
import pandas as pd

DataFrameに配列を渡せば生成

In [ ]:
data1=[['田中', 18, True],
       ['山田', 42, False],
       ['鈴木', 32, True]]
data2=[['林', 22, False],
       ['斎藤', 18, True],
       ['大田', 25, False]]

In [ ]:
df = pd.DataFrame(data1)
# numpyでも可
# df = pd.DataFrame(A)

In [ ]:
df

0   1      2
0  田中  18   True
1  山田  42  False
2  鈴木  32   True

- 列:columns 特徴とか
- 行:index データの数だけある

In [ ]:
df1 = pd.DataFrame(data1, columns=['名前','年齢', '男'])
df2 = pd.DataFrame(data2, columns=['名前','年齢', '男'])

In [ ]:
# columnsは指定しよう
df1

名前  年齢      男
0  田中  18   True
1  山田  42  False
2  鈴木  32   True

In [ ]:
# 各列はSeries
df1['年齢']

0    18
1    42
2    32
Name: 年齢, dtype: int64

In [ ]:
# 0-2行目まで表示
df[0:2]

0   1      2
0  田中  18   True
1  山田  42  False

In [ ]:
# 行にアクセスするときはlocとか
df1.loc[0]

名前      田中
年齢      18
男     True
Name: 0, dtype: object

In [ ]:
# seriesはこう
hight1 = [163,155,171]
hight2 = [160,180,163]
sr1 = pd.Series(hight1)
sr1

0    163
1    155
2    171
dtype: int64

In [ ]:
# Seriesとか配列で列を増やせる
df1['身長']=sr1
df2['身長']=hight2

In [ ]:
df1

名前  年齢      男   身長
0  田中  18   True  163
1  山田  42  False  155
2  鈴木  32   True  171

In [ ]:
# 結合できる
df_merged = pd.concat([df1,df2])

In [ ]:
# indexのリセット
df_merged = df_merged.reset_index(drop=True)

In [ ]:
# csvで出力できる
df_merged.to_csv('hoge.csv')

In [ ]:
!cat hoge.csv

,名前,年齢,男,身長
0,田中,18,True,163
1,山田,42,False,155
2,鈴木,32,True,171
3,林,22,False,160
4,斎藤,18,True,180
5,大田,25,False,163


In [ ]:
# サンプルのcsvを生成
pd.read_csv('hoge.csv', index_col=0) # index_col=0を取るとどうなる？

名前  年齢      男   身長
0  田中  18   True  163
1  山田  42  False  155
2  鈴木  32   True  171
3   林  22  False  160
4  斎藤  18   True  180
5  大田  25  False  163

統計的な処理とか

In [ ]:
# 先頭だけ表示
df.head()

0   1      2
0  田中  18   True
1  山田  42  False
2  鈴木  32   True

In [ ]:
# 平均
df_merged['年齢'].mean()
# 分散
df_merged['年齢'].std()

9.347013783378447

In [ ]:
# shape
df_merged.shape

(6, 4)

１行ごとにアクセスしたい時（めっちゃ遅い）

In [ ]:
for d in df1.iterrows():
  print(d)

(0, 名前      田中
年齢      18
男     True
身長     163
Name: 0, dtype: object)
(1, 名前       山田
年齢       42
男     False
身長      155
Name: 1, dtype: object)
(2, 名前      鈴木
年齢      32
男     True
身長     171
Name: 2, dtype: object)


In [ ]:
for d in df1.itertuples():
  print(d)
# こういうふうにアクセスできる（一応）
d.名前

Pandas(Index=0, 名前='田中', 年齢=18, 男=True, 身長=163)
Pandas(Index=1, 名前='山田', 年齢=42, 男=False, 身長=155)
Pandas(Index=2, 名前='鈴木', 年齢=32, 男=True, 身長=171)


'鈴木'